//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Hotel
{
    using System;
    using System.Collections.Generic;
    
    public partial class Application
    {
        public int ID { get; set; }
        public string PhoneNumber { get; set; }
        public int RoomID { get; set; }
        public int GuestID { get; set; }
    
        public virtual Guest Guest { get; set; }
        public virtual Room Room { get; set; }
    }
}
